### ISSUE TITLE
Crop the circles when zoomed in

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/gage-conditions#22]
This is the view on zoom currently

![image](https://user-images.githubusercontent.com/13220910/46017689-b42c4a00-c09d-11e8-9b5f-001bcfa95503.png)

Obviously, that cannot be in our final product. We need to either crop the canvas, or somehow filter the dots that get drawn. We could filter them to the specific state you click on, but seeing as hydrology does not obey political boundaries, it would probably be useful to see nearby gage conditions. If we did want to just show the ones for the state someone clicked on then I could add the state code to each points data and filter on that.

**Comment by jread-usgs** [comment]
Oh, I was referring to the cropping as this:
![image](https://user-images.githubusercontent.com/2349007/46018060-a4f9cc00-c09e-11e8-8e31-f9c70c1f9b4e.png)

I'm not bothered as much by dots in adjacent states for the MVP. But dots in the footer...we should get those cleaned up.

**Comment by lindsaycarr** [comment]
Ah - didn't see that. I wonder how that's even possible. The canvas layer doesn't go down that far. I'm also thinking we need to clean up the way the legend is crowded by the dots on zoom for the MVP.

**Comment by lindsaycarr** [comment]
Oh, you know what. It does go down that far. And for a very obvious reason: https://github.com/USGS-VIZLAB/gage-conditions/blob/master/js/app.js#L31
