### ISSUE TITLE
Process spatial data for map

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/gage-conditions#4]
will expand details for this task

**Comment by lindsaycarr** [comment]
I think this is completed thanks to #5, #12, and #15. To run the spatial processing part, you will need a few node packages: geo2svg, ndjson-cli, topojson-simplify, topojson-client, and topojson-server.

Then, you can execute: `remake::make("map_preprocess.yml")`

**Comment by lindsaycarr** [comment]
Also, you need `d3-geo-projection` node package.
